# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180909_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='phone'),
        ),
    ]
