# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180909_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='tags',
            field=models.CharField(default='', max_length=256),
        ),
    ]
