# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_loginuser_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='tags',
        ),
    ]
