# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180914_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='wealth',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='useriis',
            name='month_get',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='useriis',
            name='month_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='useriis',
            name='year_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
