# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180914_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useriis',
            name='buys',
            field=models.CharField(default='[]', max_length=2560),
        ),
        migrations.AlterField(
            model_name='useriis',
            name='sells',
            field=models.CharField(default='[]', max_length=2560),
        ),
    ]
