# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_loginuser_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
