# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_useriis_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useriis',
            old_name='day',
            new_name='days',
        ),
    ]
