# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180914_2255'),
        ('account', '0008_auto_20180914_1433'),
    ]

    operations = [
    ]
