# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180914_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='wealth',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=40),
        ),
    ]
