# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180914_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='tags',
            field=models.CharField(default='{"post": {}, "like": {}, "comment": {}}', max_length=1280),
        ),
    ]
