# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20180829_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeordis',
            unique_together=set([('user', 'post')]),
        ),
    ]
