# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180830_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeordis',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
