# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeordis',
            old_name='userprefer',
            new_name='times',
        ),
    ]
