# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180830_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='info',
            field=models.FloatField(default=0.0, verbose_name='tag_info'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=36, verbose_name='tag_name'),
            preserve_default=False,
        ),
    ]
