# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180909_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='forum.Tag', verbose_name='tags'),
        ),
    ]
