# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180910_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='diss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
